services:
  - type: web
    name: django-app
    env: python
    buildCommand: ""
    # after:
    startCommand: bash -lc "python manage.py migrate --noinput && gunicorn worksheet_site.wsgi:application"

    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: worksheet_site.settings

